version: 1.0.{build}
branches:
  only:
  - ci
skip_tags: true
environment:
  API_URI:
    secure: 09rVGQX6UZVLPq2SyXvcvX6F5s8dIq5QLyfbJEvp466HYtfrHymnq8NZCCCeMGdX
build_script:
- ps: ./Win10/Pro/x64/21H1/English.ps1