version: 1.0.{build}
branches:
  only:
  - main
skip_tags: true
environment:
  API_URI:
    secure: 09rVGQX6UZVLPq2SyXvcvX6F5s8dIq5QLyfbJEvp465H72DFLlsl5VruTU4dfKvX
build_script:
- ps: ./Win10/Pro/x64/21H1/English.ps1