name: WIN10 PRO

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  x64_21H2_English:
    runs-on: windows-2019
    timeout-minutes: 9999
    steps:
    - uses: actions/checkout@v3
    - name: Win10 Pro x64 21H2 English
      run: ./Win10/Pro/x64/21H2/English.ps1
      env:
        API_URI: ${{ secrets.API_DEV_URL }}
